export const ACTION_CHANGE_NAME = 'ACTION_CHANGE_NAME';
export const ACTION_CHANGE_SECOND_NAME = 'ACTION_CHANGE_SECOND_NAME';
export const ACTION_CHANGE_TEL = 'ACTION_CHANGE_TEL';
export const ACTION_CHANGE_ORG = 'ACTION_CHANGE_ORG';
export const ACTION_CHANGE_EMAIL = 'ACTION_CHANGE_EMAIL';
export const ACTION_GET_INITIAL_STATE = 'ACTION_GET_INITIAL_STATE';
